apiVersion: v1
kind: Deployment
metadata:
   name: wildfly
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: bangnab/wildfly-oraclejdk
        ports:
        - containerPort: 80


