apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
      port: 80 

  selector:
    app: gitlab
  clusterIP: None
  
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ext
  labels:
    app: gitlab
spec:
  ports:
    - port: 80 
  selector:
    app: gitlab
  type: LoadBalancer  

 ---
 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab   
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 22



