apiVersion: v1
kind: Service
metadata:
  name: nexus-ext
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - port: 8081 
  type: LoadBalancer  
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
    - port: 8081 
      protocol: TCP
      targetPort: 8081
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: nexus
spec:
  selector:
    matchLabels:
      app: nexus   
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8081



